/**
 * Weather → revenue regression engine.
 *
 * Faithful TypeScript port of the interactive logic in
 * `analysis/weather_dashboard.html` (generated by `analysis/build_html_dashboard.py`).
 * Operates on the REAL aggregated daily ledger + weather data in
 * `src/data/weather-daily.json` (verified to reproduce the raw ledgers to the
 * cent: Ummels €35.78M / 9,752 txns; Gilde €44.4M).
 *
 * Pipeline: daily records → group by (company, period) → sum revenue + count
 * "bad-weather" days → lag → optional season adjustment (company×month means)
 * → Spearman correlation + Student-t p-value → revenue impact split + OLS line.
 *
 * All statistics are computed in-browser so every control recomputes live,
 * exactly like the source dashboard.
 */

import weatherDailyRaw from "@/data/weather-daily.json";

// ---------------------------------------------------------------------------
// Data model
// ---------------------------------------------------------------------------

export interface DailyRecord {
  d: string; // YYYY-MM-DD (Europe/Amsterdam weather date)
  rev: number; // EUR, invoice-dated daily net (Credit − Debet)
  rain: number; // rain_mm
  snow: number;
  tmin: number; // °C
  tmean: number; // °C
  tmax: number; // °C
  wind: number; // max wind km/h
  gust: number;
}

interface CompanyBlock {
  name: string;
  records: DailyRecord[];
}

type WeatherDataset = Record<string, CompanyBlock>;

const DATA = weatherDailyRaw as unknown as WeatherDataset;

export type CompanyScope = "ummels" | "gilde" | "pooled";
export type Resolution = "weekly" | "monthly";
export type FactorId = "rain" | "frost" | "cold" | "heat" | "wind";

export interface FactorConfig {
  id: FactorId;
  label: string;
  col: keyof Pick<DailyRecord, "rain" | "tmin" | "tmean" | "tmax" | "wind">;
  dir: ">=" | "<=";
  min: number;
  max: number;
  step: number;
  defaultVal: number;
  defaultOn: boolean;
  unit: string;
  /** Short explanation of why this matters for roof work. */
  hint: string;
}

/** Factor definitions — exact thresholds/ranges from the source dashboard. */
export const FACTORS: readonly FactorConfig[] = [
  { id: "rain", label: "Rain ≥", col: "rain", dir: ">=", min: 0.5, max: 20, step: 0.5, defaultVal: 1, defaultOn: true, unit: "mm", hint: "Wet decks halt membrane and adhesive work." },
  { id: "frost", label: "Frost: min temp ≤", col: "tmin", dir: "<=", min: -5, max: 5, step: 0.5, defaultVal: 0, defaultOn: true, unit: "°C", hint: "Frost is a hard stop — adhesives and membranes will not bond." },
  { id: "cold", label: "Cold: mean temp ≤", col: "tmean", dir: "<=", min: 0, max: 12, step: 0.5, defaultVal: 5, defaultOn: false, unit: "°C", hint: "Cold slows cure times and crew productivity." },
  { id: "heat", label: "Heat: max temp ≥", col: "tmax", dir: ">=", min: 20, max: 36, step: 0.5, defaultVal: 28, defaultOn: true, unit: "°C", hint: "Heat softens bitumen and forces work to cooler hours." },
  { id: "wind", label: "Wind ≥", col: "wind", dir: ">=", min: 20, max: 60, step: 1, defaultVal: 40, defaultOn: true, unit: "km/h", hint: "High wind stops lifting and sheet handling at height." },
];

export interface FactorState {
  on: boolean;
  val: number;
}

export interface AnalysisState {
  company: CompanyScope;
  res: Resolution;
  season: boolean;
  lag: number; // 0..4
  split: number; // 20..50 (percent)
  factors: Record<FactorId, FactorState>;
}

export const DEFAULT_STATE: AnalysisState = {
  company: "ummels",
  res: "weekly",
  season: true,
  lag: 0,
  split: 33,
  factors: FACTORS.reduce(
    (acc, f) => {
      acc[f.id] = { on: f.defaultOn, val: f.defaultVal };
      return acc;
    },
    {} as Record<FactorId, FactorState>
  ),
};

export const COMPANY_OPTIONS: { id: CompanyScope; label: string }[] = [
  { id: "ummels", label: DATA.ummels?.name ?? "Peter Ummels" },
  { id: "gilde", label: DATA.gilde?.name ?? "Gilde GB" },
  { id: "pooled", label: "Pooled (both companies)" },
];

/** Map a Pidgecast opco id to a dataset company scope. */
export function opcoToCompany(opcoId: string): CompanyScope {
  return opcoId.toLowerCase().includes("gilde") ? "gilde" : "ummels";
}

// ---------------------------------------------------------------------------
// Statistics (ported verbatim from the source JS)
// ---------------------------------------------------------------------------

/** Average-rank (1-based) ranking with tie handling. */
export function rank(arr: number[]): number[] {
  const idx = arr.map((v, i) => [v, i] as [number, number]).sort((a, b) => a[0] - b[0]);
  const r = new Array<number>(arr.length);
  let i = 0;
  while (i < idx.length) {
    let j = i;
    while (j + 1 < idx.length && idx[j + 1][0] === idx[i][0]) j++;
    const avg = (i + j) / 2 + 1;
    for (let k = i; k <= j; k++) r[idx[k][1]] = avg;
    i = j + 1;
  }
  return r;
}

export function pearson(x: number[], y: number[]): number {
  const n = x.length;
  if (n === 0) return 0;
  let mx = 0;
  let my = 0;
  for (let i = 0; i < n; i++) {
    mx += x[i];
    my += y[i];
  }
  mx /= n;
  my /= n;
  let sxy = 0;
  let sx = 0;
  let sy = 0;
  for (let i = 0; i < n; i++) {
    const dx = x[i] - mx;
    const dy = y[i] - my;
    sxy += dx * dy;
    sx += dx * dx;
    sy += dy * dy;
  }
  if (sx === 0 || sy === 0) return 0;
  return sxy / Math.sqrt(sx * sy);
}

export function spearman(x: number[], y: number[]): number {
  return pearson(rank(x), rank(y));
}

const GAMMLN_COF = [
  76.18009172947146, -86.50532032941677, 24.01409824083091,
  -1.231739572450155, 0.1208650973866179e-2, -0.5395239384953e-5,
];

function gammln(xx: number): number {
  const x = xx;
  let y = xx;
  let tmp = x + 5.5;
  tmp -= (x + 0.5) * Math.log(tmp);
  let ser = 1.000000000190015;
  for (let j = 0; j < 6; j++) {
    y += 1;
    ser += GAMMLN_COF[j] / y;
  }
  return -tmp + Math.log((2.5066282746310005 * ser) / x);
}

function betacf(a: number, b: number, x: number): number {
  const FPMIN = 1e-300;
  const qab = a + b;
  const qap = a + 1;
  const qam = a - 1;
  let c = 1;
  let d = 1 - (qab * x) / qap;
  if (Math.abs(d) < FPMIN) d = FPMIN;
  d = 1 / d;
  let h = d;
  for (let m = 1; m <= 200; m++) {
    const m2 = 2 * m;
    let aa = (m * (b - m) * x) / ((qam + m2) * (a + m2));
    d = 1 + aa * d;
    if (Math.abs(d) < FPMIN) d = FPMIN;
    c = 1 + aa / c;
    if (Math.abs(c) < FPMIN) c = FPMIN;
    d = 1 / d;
    h *= d * c;
    aa = (-(a + m) * (qab + m) * x) / ((a + m2) * (qap + m2));
    d = 1 + aa * d;
    if (Math.abs(d) < FPMIN) d = FPMIN;
    c = 1 + aa / c;
    if (Math.abs(c) < FPMIN) c = FPMIN;
    d = 1 / d;
    const del = d * c;
    h *= del;
    if (Math.abs(del - 1) < 3e-7) break;
  }
  return h;
}

/** Regularized incomplete beta function I_x(a, b). */
function betai(a: number, b: number, x: number): number {
  if (x <= 0) return 0;
  if (x >= 1) return 1;
  const bt = Math.exp(
    gammln(a + b) - gammln(a) - gammln(b) + a * Math.log(x) + b * Math.log(1 - x)
  );
  if (x < (a + 1) / (a + b + 2)) return (bt * betacf(a, b, x)) / a;
  return 1 - (bt * betacf(b, a, 1 - x)) / b;
}

/** Two-sided p-value for a correlation r over n observations (Student-t). */
export function studentTPValueTwoSided(r: number, n: number): number {
  if (n < 3) return 1;
  const df = n - 2;
  const t = r * Math.sqrt(df / (1 - r * r + 1e-12));
  return betai(df / 2, 0.5, df / (df + t * t));
}

export function median(a: number[]): number {
  if (!a.length) return 0;
  const s = [...a].sort((x, y) => x - y);
  const m = Math.floor(s.length / 2);
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
}

function pearsonSlope(x: number[], y: number[]): { m: number; a: number } {
  const n = x.length;
  if (n === 0) return { m: 0, a: 0 };
  let mx = 0;
  let my = 0;
  for (let i = 0; i < n; i++) {
    mx += x[i];
    my += y[i];
  }
  mx /= n;
  my /= n;
  let sxy = 0;
  let sx = 0;
  for (let i = 0; i < n; i++) {
    sxy += (x[i] - mx) * (y[i] - my);
    sx += (x[i] - mx) ** 2;
  }
  const m = sx ? sxy / sx : 0;
  return { m, a: my - m * mx };
}

// ---------------------------------------------------------------------------
// Period aggregation
// ---------------------------------------------------------------------------

/** Period key: Monday-start week (UTC ISO date) or calendar month (YYYY-MM). */
export function periodKey(dateStr: string, res: Resolution): string {
  if (res === "monthly") return dateStr.slice(0, 7);
  const dt = new Date(dateStr + "T00:00:00Z");
  const day = (dt.getUTCDay() + 6) % 7; // 0 = Monday
  dt.setUTCDate(dt.getUTCDate() - day);
  return dt.toISOString().slice(0, 10);
}

export function isBadDay(
  rec: DailyRecord,
  factors: Record<FactorId, FactorState>
): boolean {
  for (const f of FACTORS) {
    const st = factors[f.id];
    if (!st.on) continue;
    const v = rec[f.col];
    if (f.dir === ">=" ? v >= st.val : v <= st.val) return true;
  }
  return false;
}

export interface PeriodRow {
  c: string;
  pk: string;
  rev: number;
  bad: number;
  month: number;
  badLag: number;
  revAdj: number;
  badAdj: number;
}

function buildPeriods(state: AnalysisState): PeriodRow[] {
  const recs: (DailyRecord & { _c: string })[] =
    state.company === "pooled"
      ? Object.keys(DATA).flatMap((k) =>
          DATA[k].records.map((r) => ({ ...r, _c: k }))
        )
      : (DATA[state.company]?.records ?? []).map((r) => ({
          ...r,
          _c: state.company,
        }));

  const map: Record<string, PeriodRow> = {};
  for (const r of recs) {
    const pk = periodKey(r.d, state.res);
    const key = r._c + "|" + pk;
    if (!map[key]) {
      map[key] = {
        c: r._c,
        pk,
        rev: 0,
        bad: 0,
        month: Number(state.res === "monthly" ? pk.slice(5, 7) : r.d.slice(5, 7)),
        badLag: 0,
        revAdj: 0,
        badAdj: 0,
      };
    }
    map[key].rev += r.rev;
    if (isBadDay(r, state.factors)) map[key].bad += 1;
  }

  let arr = Object.values(map).sort((a, b) => (a.pk < b.pk ? -1 : 1));

  // Lag: weather leads — period i uses bad count from i - lag (per company).
  if (state.lag > 0) {
    const byC: Record<string, PeriodRow[]> = {};
    arr.forEach((p) => {
      (byC[p.c] = byC[p.c] || []).push(p);
    });
    Object.values(byC).forEach((list) => {
      const bads = list.map((p) => p.bad);
      list.forEach((p, i) => {
        p.badLag = i - state.lag >= 0 ? bads[i - state.lag] : Number.NaN;
      });
    });
    arr = arr.filter((p) => !Number.isNaN(p.badLag));
  } else {
    arr.forEach((p) => {
      p.badLag = p.bad;
    });
  }

  // Season adjust: subtract company×month means from rev and badLag.
  if (state.season) {
    const g: Record<string, PeriodRow[]> = {};
    arr.forEach((p) => {
      const k = p.c + "|" + p.month;
      (g[k] = g[k] || []).push(p);
    });
    Object.values(g).forEach((list) => {
      const mr = list.reduce((s, p) => s + p.rev, 0) / list.length;
      const mb = list.reduce((s, p) => s + p.badLag, 0) / list.length;
      list.forEach((p) => {
        p.revAdj = p.rev - mr;
        p.badAdj = p.badLag - mb;
      });
    });
  } else {
    arr.forEach((p) => {
      p.revAdj = p.rev;
      p.badAdj = p.badLag;
    });
  }

  return arr;
}

// ---------------------------------------------------------------------------
// Public analysis API
// ---------------------------------------------------------------------------

export interface ScatterPoint {
  x: number; // badAdj
  y: number; // revAdj
}

export interface AnalysisResult {
  periods: PeriodRow[];
  n: number;
  r: number; // Spearman
  p: number; // two-sided
  significance: "significant" | "weak" | "none";
  impactPct: number;
  medianGood: number; // fewest bad days
  medianBad: number; // most bad days
  scatter: ScatterPoint[];
  fitLine: ScatterPoint[];
  enabledFactorSummary: string;
}

function significanceOf(p: number): "significant" | "weak" | "none" {
  if (p < 0.05) return "significant";
  if (p < 0.1) return "weak";
  return "none";
}

export function analyze(state: AnalysisState): AnalysisResult {
  const periods = buildPeriods(state);
  const n = periods.length;

  const badAdj = periods.map((p) => p.badAdj);
  const revAdj = periods.map((p) => p.revAdj);

  const r = n > 4 ? spearman(badAdj, revAdj) : 0;
  const p = n > 4 ? studentTPValueTwoSided(r, n) : 1;

  // Revenue impact: compare medians of low- vs high-bad-weather periods (raw rev).
  const sorted = [...periods].sort((a, b) => a.badLag - b.badLag);
  const q = Math.max(1, Math.round((periods.length * state.split) / 100));
  const low = sorted.slice(0, q).map((pp) => pp.rev);
  const high = sorted.slice(-q).map((pp) => pp.rev);
  const medianGood = median(low);
  const medianBad = median(high);
  const impactPct = medianGood > 0 ? 100 * (medianBad / medianGood - 1) : 0;

  // Scatter + OLS line over season-adjusted points.
  const scatter: ScatterPoint[] = periods.map((pp) => ({ x: pp.badAdj, y: pp.revAdj }));
  const slope = pearsonSlope(badAdj, revAdj);
  let fitLine: ScatterPoint[] = [];
  if (n > 1) {
    const xs = scatter.map((s) => s.x);
    const minX = Math.min(...xs);
    const maxX = Math.max(...xs);
    fitLine = [
      { x: minX, y: slope.m * minX + slope.a },
      { x: maxX, y: slope.m * maxX + slope.a },
    ];
  }

  const enabled = FACTORS.filter((f) => state.factors[f.id].on).map(
    (f) => `${f.label} ${state.factors[f.id].val}${f.unit}`
  );

  return {
    periods,
    n,
    r,
    p,
    significance: significanceOf(p),
    impactPct,
    medianGood,
    medianBad,
    scatter,
    fitLine,
    enabledFactorSummary: enabled.length ? enabled.join(", ") : "no factors enabled",
  };
}

export const DATASET_PROVENANCE =
  "Real aggregated ledger + Open-Meteo daily weather, 2023–2026. Verified to reproduce the raw ledgers to the cent (Ummels €35.78M / 9,752 txns; Gilde €44.4M).";
